# Generated by Django 6.0.1 on 2026-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_listing_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='store',
        ),
        migrations.AddField(
            model_name='listing',
            name='store_img_url',
            field=models.URLField(blank=True),
        ),
    ]
