# Generated by Django 6.0.1 on 2026-01-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_listing_store_listing_store_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
