# Generated by Django 6.0.1 on 2026-01-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='store_img_url',
        ),
        migrations.AddField(
            model_name='listing',
            name='store',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
