# Generated by Django 6.0.1 on 2026-01-31 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_listing_store_img_url_listing_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='store',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='name',
        ),
    ]
