# Generated by Django 6.0.1 on 2026-02-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_store_listing_domain_rename_url_listing_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(to='home.product'),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
